### ISSUE TITLE
Add absolute-zero sass mixin to `util`

### ISSUE THREAD

**Issue by cmalven** [onedesign/generator-one-base#58]
I end up adding this to almost every single project. I'm surprised it's not here already.

```scss
//===============================================================
// Absolute Zero
//===============================================================

@mixin absolute-zero {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
}
```
